### PR TITLE
Remove no-longer-supported (with Travis) Erlang version from the build process

### PR DESCRIPTION
**Pull request by paulo-ferraz-oliveira**

### CODE REVIEW

**Comment by uwiger** [comment]
Actually, I'd prefer to remove everything older than 20.3.

**Comment by paulo-ferraz-oliveira** [comment]
> Actually, I'd prefer to remove everything older than 20.3.

Sure. I can do that.

**Comment by paulo-ferraz-oliveira** [comment]
> Actually, I'd prefer to remove everything older than 20.3.

Shall we add
```
  - 21.2
  - 21.3
  - 22.0
  - 22.1
  - 22.2
  - 22.3
  - 23.0
```
as well, since we're at it?

It compiles on 23, I've tested it.

**Comment by paulo-ferraz-oliveira** [comment]
All tests are passing, in my travis-ci account. It seems, though, it's not activated for this particular repository.

**Comment by uwiger** [comment]
Good job, @tolbrino - you beat me to it. :)

**Pull request merged**
